// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseLayout: typeof import('./src/layouts/base.vue')['default']
    Breadcrumb: typeof import('./src/components/Breadcrumb.vue')['default']
    Brief: typeof import('./src/components/Brief.vue')['default']
    Content: typeof import('./src/components/Content.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Grid2: typeof import('./src/components/Grid2.vue')['default']
    Grid3: typeof import('./src/components/Grid3.vue')['default']
    Harmonic: typeof import('./src/components/Harmonic.vue')['default']
    Hero: typeof import('./src/components/Hero.vue')['default']
    HorizontalContainer: typeof import('./src/components/HorizontalContainer.vue')['default']
    HoverableLink: typeof import('./src/components/HoverableLink.vue')['default']
    IconAppNix: typeof import('~icons/app/nix')['default']
    IconFaSolidMoon: typeof import('~icons/fa-solid/moon')['default']
    IconFaSolidSun: typeof import('~icons/fa-solid/sun')['default']
    Island: typeof import('./node_modules/.pnpm/iles@0.8.7_@types+node@18.11.9/node_modules/iles/dist/client/app/components/Island.vue')['default']
    Language: typeof import('./src/components/Language.vue')['default']
    Languages: typeof import('./src/components/Languages.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    NixLogo: typeof import('./src/components/NixLogo.vue')['default']
    NixStorePath: typeof import('./src/components/NixStorePath.vue')['default']
    NixTerms: typeof import('./src/components/NixTerms.vue')['default']
    Page: typeof import('./src/components/Page.vue')['default']
    Pagination: typeof import('./src/components/Pagination.vue')['default']
    Panel: typeof import('./src/components/Panel.vue')['default']
    ReadMore: typeof import('./src/components/ReadMore.vue')['default']
    Related: typeof import('./src/components/Related.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Shell: typeof import('./src/components/Shell.vue')['default']
    SpecificLanguage: typeof import('./src/components/SpecificLanguage.vue')['default']
    Summary: typeof import('./src/components/Summary.vue')['default']
    SunIcon: typeof import('./src/components/SunIcon.vue')['default']
    Systems: typeof import('./src/components/Systems.vue')['default']
    ThemeSwitcher: typeof import('./src/components/ThemeSwitcher.vue')['default']
    Top: typeof import('./src/components/Top.vue')['default']
  }
}
