import { Document, PageFrontmatter, useDocuments } from "iles";
import { marked } from "marked";

// Quick start pages
export type QuickStartPageProps = {
  title: string;
  order: number;
};

export type QuickStartPage = Document<QuickStartPageProps>;

const quickStartPages: QuickStartPage[] =
  useDocuments<QuickStartPageProps>("~/pages/start").value;

export const sortedQuickStartPages: QuickStartPage[] = quickStartPages.sort(
  (p1: QuickStartPage, p2: QuickStartPage) => p1.order - p2.order
);

// Concept pages
export type ReadMore = {
  title: string;
  href: string;
  source?: {
    title: string;
    href: string;
  };
};

export type ConceptPageProps = {
  title: string;
  id: string; // Generated by extendFrontMatter in iles.config.ts
  snippet: string;
  readMore?: ReadMore[];
  related?: string[];
};

export type ConceptPage = Document<ConceptPageProps>;

export const conceptPages: ConceptPage[] =
  useDocuments<ConceptPageProps>("~/pages/concepts").value;

export const conceptPage = (id: string): ConceptPage =>
  conceptPages.find((page: ConceptPage) => page.id === id)!;

// Pagination
export const getPrevious = (order: number): QuickStartPage | undefined =>
  quickStartPages.find((p: QuickStartPage) => p.order === order - 1);

export const getNext = (order: number): QuickStartPage | undefined =>
  quickStartPages.find((p: QuickStartPage) => p.order === order + 1);

// Related concepts
export const relatedConceptPages = (
  currentHref: string,
  ids: string[]
): ConceptPage[] =>
  ids.map((id: string) => {
    const maybePage = conceptPages.find((page: ConceptPage) => page.id === id);
    if (maybePage === undefined) {
      throw new Error(
        `No concept page found for concept id ${id} in the front matter for page ${currentHref}`
      );
    }
    return maybePage!;
  });

// Briefs
type BriefProps = {
  id: string;
};

export type BriefPage = Document<BriefProps>;

export const getBrief = (id: string): BriefPage =>
  useDocuments<BriefProps>("~/briefs").value.find(
    (page: BriefPage) => page.id === id
  )!;

// Plain pages (like the About page)
export type PlainPageProps = {
  title: string;
  description?: string;
};

// Render small Markdown snippets without the encapsulating <p>...</p>
export const md = (input: string): string => marked.parseInline(input);

// Dropdowns
export type DropdownProps = {
  text: string;
  pages: PageFrontmatter[];
};

// Other stuff
export type ButtonProps = {
  text: string;
  href: string;
  highlight?: boolean;
};

export type BreadcrumbProps = {
  back: {
    title: string;
    href: string;
  };
  title: string;
};
